name: CI-CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{steps.generate_tag.outputs.sha}}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Setup Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Run Tests
        run: yarn test

      - name: Generate Tag
        id: generate_tag
        run: |
             SHA=$(echo $GITHUB_SHA |  head -c7) 
             echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Login in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/aula-devops-2025-2:${{steps.generate_tag.outputs.sha}} .

      - name: Push to Docker Hub  
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/aula-devops-2025-2:${{steps.generate_tag.outputs.sha}}
  
  deploy:
    name: "Deploy on Digital Ocean"
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      
      - name: Copy files to Digital Ocean
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          password: ${{secrets.PASSWORD}}
          source: "./docker-compose.yml"
          target: "~/"

      - name: Deploy on Digital Ocean
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          password: ${{secrets.PASSWORD}}
          script: |
            # Extract the commit tag for Docker Image
            TAG=${{needs.build.outputs.docker_tag}}
            # Create .env file
            [-e .env] && rm .env
            touch .env
            echo "DOCKER_IMAGE_TAG=$TAG" >> .env
            echo "DB_USER=${{secrets.DB_USER}}" >> .env
            echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> .env
            echo "DB_NAME=${{secrets.DB_NAME}}" >> .env
            echo "DB_PORT=${{secrets.DB_PORT}}" >> .env
            # Login Docker
            docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
            # Run MultiContainer
            docker compose up -d --build
          

        
        
    
